version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_USERNAME: user
      REDIS_PASSWORD: password
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
      DATABASE_URL: 'postgres://user:password@localhost:5432/dbname'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

